import React, { Suspense } from 'react';
import App from './App';

const LoadingOverlay = React.lazy(() => import('./components/LoadingOverlay'));
const RouteChangeListener = React.lazy(() => import('./components/RouteChangeListener'));
const AuthForms = React.lazy(() => import('./components/auth/AuthForms'));
const AuthModal = React.lazy(() => import('./components/auth/AuthModal'));
const LoginForm = React.lazy(() => import('./components/auth/LoginForm'));
const ProtectedRoute = React.lazy(() => import('./components/auth/ProtectedRoute'));
const RegisterForm = React.lazy(() => import('./components/auth/RegisterForm'));
const BookingModal = React.lazy(() => import('./components/bookings/BookingModal'));
const BookingsManagement = React.lazy(() => import('./components/bookings/BookingsManagement'));
const FacilitiesManagement = React.lazy(() => import('./components/facilities/FacilitiesManagement'));
const FacilityModal = React.lazy(() => import('./components/facilities/FacilityModal'));
const ActivityForm = React.lazy(() => import('./components/forms/ActivityForm'));
const BookingForm = React.lazy(() => import('./components/forms/BookingForm'));
const ClientForm = React.lazy(() => import('./components/forms/ClientForm'));
const CoachForm = React.lazy(() => import('./components/forms/CoachForm'));
const ConfirmDeleteModal = React.lazy(() => import('./components/forms/ConfirmDeleteModal'));
const PlayerForm = React.lazy(() => import('./components/forms/PlayerForm'));
const About = React.lazy(() => import('./components/landing/About'));
const Contact = React.lazy(() => import('./components/landing/Contact'));
const Features = React.lazy(() => import('./components/landing/Features'));
const Footer = React.lazy(() => import('./components/landing/Footer'));
const Hero = React.lazy(() => import('./components/landing/Hero'));
const Navigation = React.lazy(() => import('./components/landing/Navigation'));
const Stats = React.lazy(() => import('./components/landing/Stats'));
const ContextCard = React.lazy(() => import('./components/layout/ContextCard'));
const DashboardLayout = React.lazy(() => import('./components/layout/DashboardLayout'));
const Layout = React.lazy(() => import('./components/layout/Layout'));
const PageWrapper = React.lazy(() => import('./components/layout/PageWrapper'));
const ResponsiveContainer = React.lazy(() => import('./components/layout/ResponsiveContainer'));
const Sidebar = React.lazy(() => import('./components/layout/Sidebar'));
const SidebarProvider = React.lazy(() => import('./components/layout/SidebarProvider'));
const SidebarRail = React.lazy(() => import('./components/layout/SidebarRail'));
const Topbar = React.lazy(() => import('./components/layout/Topbar'));
const ModernSidebar = React.lazy(() => import('./components/layout/modernSidebar/ModernSidebar'));
const SidebarHeader = React.lazy(() => import('./components/layout/modernSidebar/SidebarHeader'));
const SidebarNavGroup = React.lazy(() => import('./components/layout/modernSidebar/SidebarNavGroup'));
const SidebarNavItem = React.lazy(() => import('./components/layout/modernSidebar/SidebarNavItem'));
const Index = React.lazy(() => import('./components/layout/modernSidebar/index'));
const SidebarConfig = React.lazy(() => import('./components/layout/modernSidebar/sidebarConfig'));
const Types = React.lazy(() => import('./components/layout/modernSidebar/types'));
const AppointmentModal = React.lazy(() => import('./components/modals/AppointmentModal'));
const StyleControlPanel = React.lazy(() => import('./components/panels/StyleControlPanel'));
const AppLogo = React.lazy(() => import('./components/ui/AppLogo'));
const Accordion = React.lazy(() => import('./components/ui/accordion'));
const AlertDialog = React.lazy(() => import('./components/ui/alert-dialog'));
const Alert = React.lazy(() => import('./components/ui/alert'));
const AspectRatio = React.lazy(() => import('./components/ui/aspect-ratio'));
const Avatar = React.lazy(() => import('./components/ui/avatar'));
const Badge = React.lazy(() => import('./components/ui/badge'));
const Breadcrumb = React.lazy(() => import('./components/ui/breadcrumb'));
const Button = React.lazy(() => import('./components/ui/button'));
const Calendar = React.lazy(() => import('./components/ui/calendar'));
const Card = React.lazy(() => import('./components/ui/card'));
const Carousel = React.lazy(() => import('./components/ui/carousel'));
const Chart = React.lazy(() => import('./components/ui/chart'));
const Checkbox = React.lazy(() => import('./components/ui/checkbox'));
const Collapsible = React.lazy(() => import('./components/ui/collapsible'));
const Command = React.lazy(() => import('./components/ui/command'));
const ContextMenu = React.lazy(() => import('./components/ui/context-menu'));
const Dialog = React.lazy(() => import('./components/ui/dialog'));
const Drawer = React.lazy(() => import('./components/ui/drawer'));
const DropdownMenu = React.lazy(() => import('./components/ui/dropdown-menu'));
const Form = React.lazy(() => import('./components/ui/form'));
const HoverCard = React.lazy(() => import('./components/ui/hover-card'));
const InputOtp = React.lazy(() => import('./components/ui/input-otp'));
const Input = React.lazy(() => import('./components/ui/input'));
const Label = React.lazy(() => import('./components/ui/label'));
const Menubar = React.lazy(() => import('./components/ui/menubar'));
const NavigationMenu = React.lazy(() => import('./components/ui/navigation-menu'));
const Pagination = React.lazy(() => import('./components/ui/pagination'));
const Popover = React.lazy(() => import('./components/ui/popover'));
const Progress = React.lazy(() => import('./components/ui/progress'));
const RadioGroup = React.lazy(() => import('./components/ui/radio-group'));
const Resizable = React.lazy(() => import('./components/ui/resizable'));
const ScrollArea = React.lazy(() => import('./components/ui/scroll-area'));
const Select = React.lazy(() => import('./components/ui/select'));
const Separator = React.lazy(() => import('./components/ui/separator'));
const Sheet = React.lazy(() => import('./components/ui/sheet'));
const Skeleton = React.lazy(() => import('./components/ui/skeleton'));
const Slider = React.lazy(() => import('./components/ui/slider'));
const Sonner = React.lazy(() => import('./components/ui/sonner'));
const Spinner = React.lazy(() => import('./components/ui/spinner'));
const Switch = React.lazy(() => import('./components/ui/switch'));
const Table = React.lazy(() => import('./components/ui/table'));
const Tabs = React.lazy(() => import('./components/ui/tabs'));
const Textarea = React.lazy(() => import('./components/ui/textarea'));
const Toast = React.lazy(() => import('./components/ui/toast'));
const Toaster = React.lazy(() => import('./components/ui/toaster'));
const ToggleGroup = React.lazy(() => import('./components/ui/toggle-group'));
const Toggle = React.lazy(() => import('./components/ui/toggle'));
const Tooltip = React.lazy(() => import('./components/ui/tooltip'));
const UseToast = React.lazy(() => import('./components/ui/use-toast'));
const Activities = React.lazy(() => import('./pages/Activities'));
const Bookings = React.lazy(() => import('./pages/Bookings'));
const Clients = React.lazy(() => import('./pages/Clients'));
const Coaches = React.lazy(() => import('./pages/Coaches'));
const Dashboard = React.lazy(() => import('./pages/Dashboard'));
const Fields = React.lazy(() => import('./pages/Fields'));
const Landing = React.lazy(() => import('./pages/Landing'));
const Login = React.lazy(() => import('./pages/Login'));
const NotFound = React.lazy(() => import('./pages/NotFound'));
const Players = React.lazy(() => import('./pages/Players'));
const PremiumDashboard = React.lazy(() => import('./pages/PremiumDashboard'));
const ResetPassword = React.lazy(() => import('./pages/ResetPassword'));
const Roles = React.lazy(() => import('./pages/Roles'));
const Settings = React.lazy(() => import('./pages/Settings'));
const Swimming = React.lazy(() => import('./pages/Swimming'));
const Users = React.lazy(() => import('./pages/Users'));
const BookingsPage = React.lazy(() => import('./pages/admin/BookingsPage'));
const FacilitiesPage = React.lazy(() => import('./pages/admin/FacilitiesPage'));
const BookingList = React.lazy(() => import('./pages/bookings/BookingList'));
const ClientList = React.lazy(() => import('./pages/clients/ClientList'));
const Collections = React.lazy(() => import('./pages/finance/Collections'));
const Pricing = React.lazy(() => import('./pages/finance/Pricing'));
const Academy = React.lazy(() => import('./pages/football/Academy'));
const Schools = React.lazy(() => import('./pages/football/Schools'));
const FreeTime = React.lazy(() => import('./pages/swimming/FreeTime'));
const FreeTimeBookings = React.lazy(() => import('./pages/swimming/FreeTimeBookings'));
const Private = React.lazy(() => import('./pages/swimming/Private'));
const PrivateBookings = React.lazy(() => import('./pages/swimming/PrivateBookings'));
const SchoolsBookings = React.lazy(() => import('./pages/swimming/SchoolsBookings'));
const SwimmingTabs = React.lazy(() => import('./pages/swimming/SwimmingTabs'));
const UserList = React.lazy(() => import('./pages/users/UserList'));

function LazyApp() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <App />
    </Suspense>
  );
}

export default LazyApp;
export { LoadingOverlay, RouteChangeListener, AuthForms, AuthModal, LoginForm, ProtectedRoute, RegisterForm, BookingModal, BookingsManagement, FacilitiesManagement, FacilityModal, ActivityForm, BookingForm, ClientForm, CoachForm, ConfirmDeleteModal, PlayerForm, About, Contact, Features, Footer, Hero, Navigation, Stats, ContextCard, DashboardLayout, Layout, PageWrapper, ResponsiveContainer, Sidebar, SidebarProvider, SidebarRail, Topbar, ModernSidebar, SidebarHeader, SidebarNavGroup, SidebarNavItem, Index, SidebarConfig, Types, AppointmentModal, StyleControlPanel, AppLogo, Accordion, AlertDialog, Alert, AspectRatio, Avatar, Badge, Breadcrumb, Button, Calendar, Card, Carousel, Chart, Checkbox, Collapsible, Command, ContextMenu, Dialog, Drawer, DropdownMenu, Form, HoverCard, InputOtp, Input, Label, Menubar, NavigationMenu, Pagination, Popover, Progress, RadioGroup, Resizable, ScrollArea, Select, Separator, Sheet, Skeleton, Slider, Sonner, Spinner, Switch, Table, Tabs, Textarea, Toast, Toaster, ToggleGroup, Toggle, Tooltip, UseToast, Activities, Bookings, Clients, Coaches, Dashboard, Fields, Landing, Login, NotFound, Players, PremiumDashboard, ResetPassword, Roles, Settings, Swimming, Users, BookingsPage, FacilitiesPage, BookingList, ClientList, Collections, Pricing, Academy, Schools, FreeTime, FreeTimeBookings, Private, PrivateBookings, SchoolsBookings, SwimmingTabs, UserList };
