// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdknshctupurizhdparr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFka25zaGN0dXB1cml6aGRwYXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTQ4ODUsImV4cCI6MjA2NTY5MDg4NX0.VXs-zsb4VqjTArrUY9kxvDAIiMcBoQmVVCpwMI0p634";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);